spring.application.name=maonamassa
server.port=3000
spring.datasource.url=jdbc:postgresql://localhost:5432/maona_massa
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

jwt.secret = MAONAMASSA@123#

security.token.secret.profissional = MAONAMASSA@123#PROFISSIONAL
security.token.secret.contratante = MAONAMASSA@123#CONTRATANTE